### ISSUE TITLE
StopIteration Error when connecting to a tyo-mq server with service over http/https  

### ISSUE THREAD

**Issue by e-tang** [tyolab/tyo-mq-client-python#1]
```bash
tyo-mq-client-python$
./test.py
```
```
Connecting to the tyo-mq server: localhost
('creating subscriber: TYO Lab',) {}
('creating producer: TYO Lab',) {}
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/data/tyolab/python/tyo-mq-client/test.py", line 76, in <module>
    producer.connect(-1)
  File "/data/tyolab/python/tyo-mq-client/tyo_mq_client/socket.py", line 106, in connect
    self.socket = SocketIO(self.host, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
StopIteration
```

**Comment by tyodev** [comment]
Please make sure the host is set up properly:

```python
producer.host = "https:/www.example.com:443"
``` 

Not

```python
producer.host = "https:/www.example.com:443/"
```
